server:
  port: 9999
spring:
  application:
    name: user-center
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://www.wangyiyun.top:3306/user-center?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: www.wangyiyun.top
    port: 6379
    password:
mybatis:
  type-aliases-package: com.example.domain
  mapper-locations: classpath:mapper/*.xml