server:
  port: 9999
spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.4.7.100:13306/user-center?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 10.4.7.100
    port: 6379
    password:
mybatis:
  type-aliases-package: com.example.domain
  mapper-locations: classpath:mapper/*.xml